name:                HiVM
version:             0.1.0.0
github:              "imkiva/HiVM"
license:             MIT
author:              "Kiva"
maintainer:          "libkernelpanic@gmail.com"
copyright:           "Copyright (c) 2018 Kiva"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            categories

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/imkiva/HiVM#readme>

dependencies:
- base >= 4.7 && < 5
- fgl
- fingertree
- zlib
- pretty
- array
- binary
- bytestring
- containers
- data-binary-ieee754
- deepseq
- directory
- filepath
- unordered-containers
- hashable
- random
- stm
- mtl
- split

ghc-options: -Wall

library:
  source-dirs: src

executables:
  HiVM-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HiVM

tests:
  HiVM-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HiVM
