{-
 - Generated by generate-constants-hs.sh. DO NOT MODIFY!
-}
module ClassFile.Constants where

cITEMTop = 0

cITEMInteger = 1

cITEMFloat = 2

cITEMDouble = 3

cITEMLong = 4

cITEMNull = 5

cITEMUninitializedThis = 6

cITEMObject = 7

cITEMUninitialized = 8

cATTRIBUTEConstantValue = 0

cATTRIBUTECode = 1

cATTRIBUTEStackMapTable = 2

cATTRIBUTEExceptions = 3

cATTRIBUTEInnerClasses = 4

cATTRIBUTEEnclosingMethod = 5

cATTRIBUTESynthetic = 6

cATTRIBUTESignature = 7

cATTRIBUTESourceFile = 8

cATTRIBUTESourceDebugExtension = 9

cATTRIBUTELineNumberTable = 10

cATTRIBUTELocalVariableTable = 11

cATTRIBUTELocalVariableTypeTable = 12

cATTRIBUTEDeprecated = 13

cATTRIBUTERuntimeVisibleAnnotations = 14

cATTRIBUTERuntimeInvisibleAnnotations = 15

cATTRIBUTERuntimeVisibleParameterAnnotations = 16

cATTRIBUTERuntimeInvisibleParameterAnnotations = 17

cATTRIBUTERuntimeVisibleTypeAnnotations = 18

cATTRIBUTERuntimeInvisibleTypeAnnotations = 19

cATTRIBUTEAnnotationDefault = 20

cATTRIBUTEBootstrapMethods = 21

cATTRIBUTEMethodParameters = 22

cCONSTANTUtf8 = 1

cCONSTANTInteger = 3

cCONSTANTFloat = 4

cCONSTANTLong = 5

cCONSTANTDouble = 6

cCONSTANTClass = 7

cCONSTANTString = 8

cCONSTANTFieldref = 9

cCONSTANTMethodref = 10

cCONSTANTInterfaceMethodref = 11

cCONSTANTNameAndType = 12

cCONSTANTMethodHandle = 15

cCONSTANTMethodType = 16

cCONSTANTInvokeDynamic = 18

cREFgetField = 1

cREFgetStatic = 2

cREFputField = 3

cREFputStatic = 4

cREFinvokeVirtual = 5

cREFinvokeStatic = 6

cREFinvokeSpecial = 7

cREFnewInvokeSpecial = 8

cREFinvokeInterface = 9
